CREATE TABLE scouts(
    ci PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    rama VARCHAR(255) NOT NULL,
    unidad VARCHAR(255) NOT NULL,
    etapa VARCHAR(255) NOT NULL
)
ALTER TABLE scout ADD COLUMN dirigente_ci  REFERENCES dirigente(ci);

CREATE TABLE dirigente (
    ci INTEGER PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    apellido VARCHAR(200) NOT NULL,
    unidad VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upadate_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE dirigente ADD COLUMN gravatar VARCHAR(250);